.gitmodules, CMakeLists.txt, build_tools/third_party/cudnn-frontend/CMakeLists.txt, runtime/src/CMakeLists.txt, runtime/src/openxla/runtime/nvgpu/CMakeLists.txt, runtime/src/openxla/runtime/nvgpu/cudnn_api.cpp, runtime/src/openxla/runtime/nvgpu/cudnn_api.h, runtime/src/openxla/runtime/nvgpu/cudnn_module.cpp, runtime/src/openxla/runtime/nvgpu/cudnn_module.h, runtime/src/openxla/runtime/nvgpu/cudnn_stub.cpp, runtime/src/openxla/runtime/nvgpu/cudnn_stub.h, runtime/src/openxla/runtime/nvgpu/cudnn_stub.h.inc, runtime/src/openxla/runtime/nvgpu/dynamic_symbol_tables.h, runtime/src/openxla/runtime/nvgpu/dynamic_symbols.c, runtime/src/openxla/runtime/nvgpu/dynamic_symbols.h, runtime/src/openxla/runtime/nvgpu/status_util.h, runtime/src/openxla/runtime/nvgpu/test/example.mlir, tools/openxla-runner.c
Initial support for constructing cuDNN graphs:
1. `@cudnn.tensor.arg` - creates tensor arguments
2. `@cudnn.pointwise_relu` - creates Relu operation
3. `@cudnn.create.graph` - creates an operation graph
Adds `cudnn_frontend` as a dependency.
=> [cuDNN] Add basic support for constructing cuDNN graphs

compiler/src/openxla/compiler/nvgpu/Dialect/CUDNN/IR/CUDNNOps.td, compiler/src/openxla/compiler/nvgpu/Dialect/CUDNN/IR/test/ops.mlir, compiler/src/openxla/compiler/nvgpu/Dialect/CUDNN/Transforms/BUILD.bazel, compiler/src/openxla/compiler/nvgpu/Dialect/CUDNN/Transforms/CMakeLists.txt, compiler/src/openxla/compiler/nvgpu/Dialect/CUDNN/Transforms/ExpandCUDNNOperations.cpp, compiler/src/openxla/compiler/nvgpu/Dialect/CUDNN/Transforms/Passes.h, compiler/src/openxla/compiler/nvgpu/Dialect/CUDNN/Transforms/Passes.td, compiler/src/openxla/compiler/nvgpu/Dialect/CUDNN/Transforms/test/expand_batch_norm.mlir, compiler/src/openxla/compiler/nvgpu/PluginRegistration.cpp, runtime/src/openxla/runtime/nvgpu/test/conv2d_batch_norm.mlir
Add an `openxla-nvgpu-expand-cudnn-operations` pass for expanding batch norm into pointwise operations, that later could be fused with convolution using cuDNN runtime fusion engine
=> [cuDNN] Add e2e test for Conv2D + BatchNorm

compiler/src/openxla/compiler/nvgpu/Conversion/ConvertHLOToCUDNN.cpp, compiler/src/openxla/compiler/nvgpu/Dialect/CUDNN/Conversion/ConvertCUDNNToRuntime.cpp, compiler/src/openxla/compiler/nvgpu/Dialect/CUDNN/IR/BUILD.bazel, compiler/src/openxla/compiler/nvgpu/Dialect/CUDNN/IR/CMakeLists.txt, compiler/src/openxla/compiler/nvgpu/Dialect/CUDNN/IR/CUDNNOps.cpp, compiler/src/openxla/compiler/nvgpu/Dialect/CUDNN/IR/CUDNNOps.h, compiler/src/openxla/compiler/nvgpu/Dialect/CUDNN/IR/CUDNNOps.td, compiler/src/openxla/compiler/nvgpu/Dialect/CUDNN/IR/test/ops.mlir, compiler/src/openxla/compiler/nvgpu/Dialect/CUDNN/Transforms/test/cudnn_to_runtime.mlir, runtime/src/openxla/runtime/nvgpu/cudnn_api.cpp, runtime/src/openxla/runtime/nvgpu/cudnn_api.h, runtime/src/openxla/runtime/nvgpu/cudnn_module.cpp, runtime/src/openxla/runtime/nvgpu/test/conv2d_add_bias.mlir
Context: https://github.com/openxla/iree/issues/13313
Custom modules when loaded dynamically don't have access to the HAL device, so for this reason `cudnn.handle` construction has to be explicit in the IR.
=> [cuDNN] Add explicit cudnn handle argument to cudnn call op

README.md
Added two more lines to explain where the `iree` repo needs to live to make this work. My `iree` repository had a different name...
=> Expand the readme a little

compiler/src/openxla/compiler/nvgpu/Dialect/CUDNN/IR/CUDNNOps.cpp, compiler/src/openxla/compiler/nvgpu/Dialect/CUDNN/IR/CUDNNTypes.td, runtime/src/openxla/runtime/nvgpu/cudnn_api.cpp, runtime/src/openxla/runtime/nvgpu/cudnn_api.h, runtime/src/openxla/runtime/nvgpu/cudnn_module.cpp, runtime/src/openxla/runtime/nvgpu/test/conv2d_add_bias.mlir
Add `KHWC` and `KCHW` filter tensor layouts to avoid confusion from using `NHWC` layout for convolution filters
See diff: https://github.com/ezhulenev/openxla-nvgpu/compare/compute-type...ezhulenev:openxla-nvgpu:filter-layouts
=> [cuDNN] Add filter tensor layouts

CMakeLists.txt, runtime/src/openxla/runtime/nvgpu/cudnn_module.cpp, runtime/src/openxla/runtime/nvgpu/cudnn_module.h, tools/openxla-runner.cpp
Use static linking mechanism to always link cuDNN module into `iree-run-module` and `iree-benchmark-module`
=> Statically link cuDNN module into IREE tools

CMakeLists.txt, runtime/src/lit.cfg.py, runtime/src/openxla/runtime/nvgpu/CMakeLists.txt, runtime/src/openxla/runtime/nvgpu/benchmark/CMakeLists.txt, runtime/src/openxla/runtime/nvgpu/benchmark/conv2d_add_bias_cudnn.mlir, runtime/src/openxla/runtime/nvgpu/benchmark/conv2d_add_bias_mhlo.mlir, runtime/src/openxla/runtime/nvgpu/test/CMakeLists.txt, runtime/src/openxla/runtime/nvgpu/test/conv2d.mlir, runtime/src/openxla/runtime/nvgpu/test/conv2d_add_bias.mlir, runtime/src/openxla/runtime/nvgpu/test/conv2d_batch_norm.mlir, runtime/src/openxla/runtime/nvgpu/test/conv2d_batch_norm_add_max.mlir, runtime/src/openxla/runtime/nvgpu/test/conv2d_batch_norm_expanded.mlir
```
ctest --test-dir build -R openxla/runtime/nvgpu/
Internal ctest changing into directory: /usr/local/google/home/ezhulenev/a6000/openxla-nvgpu/build
Test project /usr/local/google/home/ezhulenev/a6000/openxla-nvgpu/build
Start 1041: openxla/runtime/nvgpu/benchmark/conv2d_add_bias_cudnn.mlir.test
1/7 Test #1041: openxla/runtime/nvgpu/benchmark/conv2d_add_bias_cudnn.mlir.test ...   Passed    2.43 sec
Start 1042: openxla/runtime/nvgpu/benchmark/conv2d_add_bias_mhlo.mlir.test
2/7 Test #1042: openxla/runtime/nvgpu/benchmark/conv2d_add_bias_mhlo.mlir.test ....   Passed    5.73 sec
Start 1043: openxla/runtime/nvgpu/test/conv2d_add_bias.mlir.test
3/7 Test #1043: openxla/runtime/nvgpu/test/conv2d_add_bias.mlir.test ..............   Passed   12.15 sec
Start 1044: …
```
=> Configure runtime LIT tests

runtime/src/openxla/runtime/nvgpu/cudnn_api.cpp
For the moment we just have a hard dependency that this will be used only on CUDA.
=> Adapt to `isa` being removed.

.gitmodules
openai/triton@17eb982771e939406b6f801d80d51498507893dd
The commit that the submodule points to at the moment does not contain the required patches that were mentioned in #76. These patches have landed in the meantime, so we can use openai/triton directly.
=> Update triton submodule to HEAD

.gitmodules, compiler/src/openxla/compiler/nvgpu/PluginRegistration.cpp
Add a new plugin option to specify a transform dialect script that
should be executed as part of the preprocessing pipeline. This makes it
possible to perform GPU-specific preprocessing without a custom hook in
one of the IREE pipelines.
Usage:
```
iree-compile ... --iree_plugin=openxla-transform -openxla-transform-preprocessing=file.mlir
```
Depends on #83.
=> Add transform dialect interpreter preprocessing plugin

compiler/src/openxla/compiler/nvgpu/Dialect/CUDNN/Conversion/ConvertCUDNNToRuntime.cpp, runtime/src/openxla/runtime/nvgpu/cudnn/test/e2e_conv2d.mlir
Broken by PR 82
Outline multiple ops in HLO to CUDNN lowering (https://github.com/openxla/openxla-nvgpu/pull/82)
=> Fix e2e conv2d test

compiler/src/openxla/compiler/nvgpu/Dialect/TritonFlow/Conversion/ConvertTritonToFlowDispatch.cpp, compiler/src/openxla/compiler/nvgpu/Dialect/TritonFlow/IR/BUILD.bazel, compiler/src/openxla/compiler/nvgpu/Dialect/TritonFlow/IR/CMakeLists.txt, compiler/src/openxla/compiler/nvgpu/Dialect/TritonFlow/IR/TritonFlowDialect.td, compiler/src/openxla/compiler/nvgpu/Dialect/TritonFlow/IR/TritonFlowOps.cpp, compiler/src/openxla/compiler/nvgpu/Dialect/TritonFlow/IR/TritonFlowOps.h, compiler/src/openxla/compiler/nvgpu/Dialect/TritonFlow/IR/TritonFlowOps.td, compiler/src/openxla/compiler/nvgpu/Dialect/TritonFlow/IR/test/BUILD.bazel, compiler/src/openxla/compiler/nvgpu/Dialect/TritonFlow/IR/test/CMakeLists.txt, compiler/src/openxla/compiler/nvgpu/Dialect/TritonFlow/IR/test/invalid.mlir, compiler/src/openxla/compiler/nvgpu/Dialect/TritonFlow/IR/test/ops.mlir, compiler/src/openxla/compiler/nvgpu/Dialect/TritonFlow/Transforms/test/triton_to_flow_dispatch.mlir, runtime/src/openxla/runtime/nvgpu/triton/test/triton_add_kernel.mlir
Also renamed `triton.dispatch` to `triton.call`. `TritonCallOp` will be the entry point into the Triton plugin, easy to use externally, and `triton.executable` + `triton.dispatch` will be an internal implementation detail.
=> [Triton] Add triton executable ops + verifiers + tests

README.md, sync_deps.py
These pins just resolve to the 'nightly' rolling schedule to get started and may not build. Next step will be to bootstrap the CI off of them.
=> Add dependency pins and update README with project maintenance steps.

compiler/src/openxla/compiler/nvgpu/Conversion/ConvertHLOToCUDNN.cpp, compiler/src/openxla/compiler/nvgpu/Transforms/test/hlo_to_cudnn.mlir, runtime/src/openxla/runtime/nvgpu/cudnn/test/e2e_conv2d.mlir, runtime/src/openxla/runtime/nvgpu/cudnn/test/e2e_resnet50_subset.mlir
With CUDNN we are now ~6x faster than codegen for a single convolution. Measured 0.104 ms with CUDNN vs 0.671 ms w/o CUDNN on NVIDIA RTX A6000.
=> Build CUDNN graph on module initialization

compiler/src/openxla/compiler/nvgpu/Dialect/TritonFlow/IR/TritonFlowOps.cpp, compiler/src/openxla/compiler/nvgpu/Dialect/TritonFlow/IR/test/invalid.mlir, compiler/src/openxla/compiler/nvgpu/Dialect/TritonFlow/IR/test/ops.mlir, compiler/src/openxla/compiler/nvgpu/Dialect/TritonFlow/Transforms/OutlineTritonCalls.cpp, compiler/src/openxla/compiler/nvgpu/Dialect/TritonFlow/Transforms/test/outline_triton_calls.mlir
* Update `triton.call` and `triton.dispatch` verifiers to correctly handle tied results.
* Fix pipeline layout (ABI) inference for tied layouts
* Update outlining pass to correctly handle tied results
* Forward argument attributes to outlined triton executable
=> [Triton] Add support for outlining Triton calls with tied results

compiler/src/openxla/compiler/nvgpu/Dialect/TritonFlow/IR/TritonFlowOps.cpp, compiler/src/openxla/compiler/nvgpu/Dialect/TritonFlow/IR/TritonFlowOps.td, compiler/src/openxla/compiler/nvgpu/Dialect/TritonFlow/Transforms/BUILD.bazel, compiler/src/openxla/compiler/nvgpu/Dialect/TritonFlow/Transforms/CMakeLists.txt, compiler/src/openxla/compiler/nvgpu/Dialect/TritonFlow/Transforms/OutlineTritonCalls.cpp, compiler/src/openxla/compiler/nvgpu/Dialect/TritonFlow/Transforms/Passes.h, compiler/src/openxla/compiler/nvgpu/Dialect/TritonFlow/Transforms/Passes.td, compiler/src/openxla/compiler/nvgpu/Dialect/TritonFlow/Transforms/RefineTritonAbi.cpp, compiler/src/openxla/compiler/nvgpu/Dialect/TritonFlow/Transforms/test/BUILD.bazel, compiler/src/openxla/compiler/nvgpu/Dialect/TritonFlow/Transforms/test/CMakeLists.txt, compiler/src/openxla/compiler/nvgpu/Dialect/TritonFlow/Transforms/test/outline_triton_calls.mlir, compiler/src/openxla/compiler/nvgpu/Dialect/TritonFlow/Transforms/test/refine_triton_abi.mlir
Diff: https://github.com/ezhulenev/openxla-nvgpu/compare/triton-5...ezhulenev:openxla-nvgpu:triton-6
IREE ABI will require non-trivial type conversion for passing scalar types, so it's easier to keep trivial outlining separately.
=> [Triton] NFC: Split Triton ABI refinement into a separate pass

runtime/src/openxla/runtime/nvgpu/cudnn/benchmark/conv2d_add_bias_cudnn.mlir, runtime/src/openxla/runtime/nvgpu/cudnn/benchmark/conv2d_add_bias_mhlo.mlir, runtime/src/openxla/runtime/nvgpu/cudnn/test/conv2d.mlir, runtime/src/openxla/runtime/nvgpu/cudnn/test/conv2d_1x1_add_bias.mlir, runtime/src/openxla/runtime/nvgpu/cudnn/test/conv2d_3x3_add_bias.mlir, runtime/src/openxla/runtime/nvgpu/cudnn/test/conv2d_add_bias.mlir, runtime/src/openxla/runtime/nvgpu/cudnn/test/conv2d_batch_norm.mlir, runtime/src/openxla/runtime/nvgpu/cudnn/test/conv2d_batch_norm_add_max.mlir, runtime/src/openxla/runtime/nvgpu/cudnn/test/conv2d_batch_norm_expanded.mlir, runtime/src/openxla/runtime/nvgpu/cudnn/test/conv2d_freduce.mlir, runtime/src/openxla/runtime/nvgpu/triton/test/triton_add.mlir, runtime/src/openxla/runtime/nvgpu/triton/test/triton_custom_call_add.mlir
IREE no longer supports MHLO. Update tests to use stablehlo instead.
=> Fix runtime tests after dependency sync

CMakeLists.txt, runtime/src/openxla/runtime/nvgpu/cudnn/test/python/conv2d_test.py
Python test passes with these changes, however we need to clean it up and figure out how to avoid building llvm-cpu backend
```
ctest --test-dir build -R conv2d_test
```
=> [cudnn] Fix python tests

CMakeLists.txt
Fix landed in IREE: https://github.com/openxla/iree/commit/59fd431f2ae71c5eb01789e7aa05622ac2dd5a0f, we no longer need to build llvm-cpu backend to run python tests
=> Disable llvm-cpu backend

compiler/src/openxla/compiler/nvgpu/Dialect/FlowTransformExtension/IR/test/interpreter.mlir
Fix mlir test after renaming callback in previous CL. This should bring CI back to green state.
=> [FlowTransform] Fix interpreter test
