AUTHORS
Adding NVIDIA to the authors list
=> Update AUTHORS to include NVIDIA

compiler/src/openxla/compiler/nvgpu/Dialect/CUDNN/IR/CUDNNOps.cpp, compiler/src/openxla/compiler/nvgpu/Dialect/CUDNN/IR/CUDNNOps.h, compiler/src/openxla/compiler/nvgpu/Dialect/CUDNN/IR/CUDNNOps.td, compiler/src/openxla/compiler/nvgpu/Dialect/CUDNN/IR/test/invalid.mlir, compiler/src/openxla/compiler/nvgpu/Dialect/CUDNN/IR/test/ops.mlir
Add `cudnn.graph` operation for outlining cuDNN-compatible computations into separate function-like operations
=> [cuDNN] Add cudnn.graph operation to cuDNN dialect

compiler/src/openxla/compiler/nvgpu/Dialect/CUDNN/IR/CUDNNDialect.td, compiler/src/openxla/compiler/nvgpu/Dialect/CUDNN/IR/CUDNNOps.cpp, compiler/src/openxla/compiler/nvgpu/Dialect/CUDNN/IR/CUDNNOps.td, compiler/src/openxla/compiler/nvgpu/Dialect/CUDNN/IR/test/invalid.mlir, compiler/src/openxla/compiler/nvgpu/Dialect/CUDNN/IR/test/ops.mlir
Diff base: https://github.com/openxla/openxla-nvgpu/pull/9
=> [cuDNN] Add cudnn.call operation for calling cuDNN graphs

runtime/src/openxla/runtime/nvgpu/cudnn_module.cpp, runtime/src/openxla/runtime/nvgpu/test/example.mlir
Update type registration to catch up with IREE changes in https://github.com/openxla/iree/commit/09630d681de3826e5d5d29e6ce3c53a26f2ee9f2
=> [cuDNN] Update VM type registration to latest IREE version

compiler/src/openxla/compiler/nvgpu/Dialect/CUDNN/Conversion/ConvertCUDNNToRuntime.cpp, compiler/src/openxla/compiler/nvgpu/Dialect/CUDNN/IR/CUDNNTypes.td, compiler/src/openxla/compiler/nvgpu/Dialect/CUDNN/Transforms/test/cudnn_to_runtime.mlir
Also add support for non-fp32 cuDNN data types
=> [cuDNN] Add support for lowering cuDNN tensors with layouts

compiler/src/openxla/compiler/nvgpu/Dialect/CUDNN/Conversion/ConvertCUDNNToRuntime.cpp, compiler/src/openxla/compiler/nvgpu/Dialect/CUDNN/IR/CUDNNOps.td, compiler/src/openxla/compiler/nvgpu/Dialect/CUDNN/IR/test/ops.mlir, compiler/src/openxla/compiler/nvgpu/Dialect/CUDNN/Transforms/test/cudnn_to_runtime.mlir, runtime/src/openxla/runtime/nvgpu/cudnn_api.cpp, runtime/src/openxla/runtime/nvgpu/cudnn_api.h, runtime/src/openxla/runtime/nvgpu/cudnn_module.cpp, runtime/src/openxla/runtime/nvgpu/test/conv2d_add_bias.mlir
Add support for running https://docs.nvidia.com/deeplearning/cudnn/developer-guide/index.html#convbiasact pre-compiled cuDNN engine
=> [cuDNN] Add e2e example for Conv2D + Add + Bias fusion

compiler/src/openxla/compiler/nvgpu/Dialect/CUDNN/Conversion/ConvertCUDNNToRuntime.cpp, compiler/src/openxla/compiler/nvgpu/Dialect/CUDNN/IR/BUILD.bazel, compiler/src/openxla/compiler/nvgpu/Dialect/CUDNN/IR/CMakeLists.txt, compiler/src/openxla/compiler/nvgpu/Dialect/CUDNN/IR/CUDNNDialect.cpp, compiler/src/openxla/compiler/nvgpu/Dialect/CUDNN/IR/CUDNNDialect.h, compiler/src/openxla/compiler/nvgpu/Dialect/CUDNN/IR/CUDNNDialect.td, compiler/src/openxla/compiler/nvgpu/Dialect/CUDNN/IR/CUDNNOps.cpp, compiler/src/openxla/compiler/nvgpu/Dialect/CUDNN/IR/CUDNNOps.h, compiler/src/openxla/compiler/nvgpu/Dialect/CUDNN/IR/CUDNNOps.td, compiler/src/openxla/compiler/nvgpu/Dialect/CUDNN/IR/CUDNNTypes.td, compiler/src/openxla/compiler/nvgpu/Dialect/CUDNN/IR/test/ops.mlir, compiler/src/openxla/compiler/nvgpu/Dialect/CUDNN/Transforms/test/cudnn_to_runtime.mlir, runtime/src/openxla/runtime/nvgpu/cudnn_api.cpp, runtime/src/openxla/runtime/nvgpu/cudnn_api.h, runtime/src/openxla/runtime/nvgpu/cudnn_module.cpp, runtime/src/openxla/runtime/nvgpu/test/conv2d_batch_norm_expanded.mlir
* Also add support for specifying convolution mode for Conv operations
* Add a test for running expanded Conv2D + batch norm fusion
=> [cuDNN] Add support for pointwise binary/unary ops

compiler/src/openxla/compiler/nvgpu/Conversion/ConvertHLOToCUDNN.cpp, compiler/src/openxla/compiler/nvgpu/Conversion/ConvertHLOToCUDNN.h, compiler/src/openxla/compiler/nvgpu/Transforms/ConvertHLOToCUDNN.cpp, compiler/src/openxla/compiler/nvgpu/test/example.mlir
Currently expects NCHW layout and bails out otherwise.
=> [cuDNN] Add lowering of stablehlo.conv.

compiler/src/openxla/compiler/nvgpu/Conversion/ConvertHLOToCUDNN.cpp
Forgot to commit changes required from rebase.
=> Fix for 9f8efcf.

runtime/src/openxla/runtime/nvgpu/cudnn_api.cpp, runtime/src/openxla/runtime/nvgpu/cudnn_api.h, runtime/src/openxla/runtime/nvgpu/cudnn_module.cpp, runtime/src/openxla/runtime/nvgpu/cudnn_stub.cpp, runtime/src/openxla/runtime/nvgpu/cudnn_stub.h, runtime/src/openxla/runtime/nvgpu/cudnn_stub.h.inc
Rename `CuDNN` to `Cudnn` in all types defined under runtime folder
=> [cuDNN] NFC: Cleanup capitalization in runtime

runtime/src/openxla/runtime/nvgpu/benchmark/conv2d_add_bias_cudnn.mlir, runtime/src/openxla/runtime/nvgpu/benchmark/conv2d_add_bias_mhlo.mlir, runtime/src/openxla/runtime/nvgpu/cudnn_api.cpp, runtime/src/openxla/runtime/nvgpu/cudnn_api.h, runtime/src/openxla/runtime/nvgpu/cudnn_module.cpp
* Also check that input buffers are correctly aligned
* Sync with host after dispatching cuDNN plan on a default stream
=> [cuDNN] Add cuDNN vs MHLO benchmarks for Conv2D

runtime/src/openxla/runtime/nvgpu/CMakeLists.txt, runtime/src/openxla/runtime/nvgpu/benchmark/conv2d_add_bias_cudnn.mlir, runtime/src/openxla/runtime/nvgpu/benchmark/conv2d_add_bias_mhlo.mlir, runtime/src/openxla/runtime/nvgpu/cudnn_api.cpp, runtime/src/openxla/runtime/nvgpu/cudnn_api.h, runtime/src/openxla/runtime/nvgpu/cudnn_module.cpp, runtime/src/openxla/runtime/nvgpu/test/conv2d_add_bias.mlir
* add support for passing convolution stride, padding and dilation
* add tests for 3x3 conv2d
* add benchmarks for 3x3 conv2d
=> [cuDNN] Add support for Conv padding

compiler/src/openxla/compiler/nvgpu/Dialect/CUDNN/Transforms/test/cudnn_to_runtime.mlir, compiler/src/openxla/compiler/nvgpu/Dialect/CUDNN/Transforms/test/expand_batch_norm.mlir, compiler/src/openxla/compiler/nvgpu/Transforms/test/example.mlir
Use pass flags in `iree-opt` after fix in https://github.com/openxla/iree/pull/13388
=> Use registered passes through  flags after fix

runtime/src/openxla/runtime/nvgpu/cudnn_api.cpp, runtime/src/openxla/runtime/nvgpu/cudnn_api.h, runtime/src/openxla/runtime/nvgpu/cudnn_module.cpp
Resolve few TODOs by generalizing strides to permutation, and permutation to strides computation.
=> [cuDNN] Generalize strides computations

compiler/src/openxla/compiler/nvgpu/Dialect/TritonFlow/Conversion/ConvertTritonToFlowDispatch.cpp, compiler/src/openxla/compiler/nvgpu/Dialect/TritonFlow/IR/TritonFlowOps.cpp, compiler/src/openxla/compiler/nvgpu/Dialect/TritonFlow/IR/TritonFlowOps.h, compiler/src/openxla/compiler/nvgpu/Dialect/TritonFlow/IR/TritonFlowOps.td, compiler/src/openxla/compiler/nvgpu/Dialect/TritonFlow/IR/test/ops.mlir, compiler/src/openxla/compiler/nvgpu/Dialect/TritonFlow/Transforms/test/triton_to_flow_dispatch.mlir, runtime/src/openxla/runtime/nvgpu/triton/test/triton_add_kernel.mlir
Diff: https://github.com/ezhulenev/openxla-nvgpu/compare/triton-1...ezhulenev:openxla-nvgpu:triton-2
=> [Triton] Add support for dynamic dims and tied operands

compiler/src/openxla/compiler/nvgpu/Dialect/TritonFlow/IR/TritonFlowOps.cpp, compiler/src/openxla/compiler/nvgpu/Dialect/TritonFlow/IR/TritonFlowOps.td, compiler/src/openxla/compiler/nvgpu/Dialect/TritonFlow/Transforms/BUILD.bazel, compiler/src/openxla/compiler/nvgpu/Dialect/TritonFlow/Transforms/CMakeLists.txt, compiler/src/openxla/compiler/nvgpu/Dialect/TritonFlow/Transforms/OutlineTritonCalls.cpp, compiler/src/openxla/compiler/nvgpu/Dialect/TritonFlow/Transforms/PassDetail.h, compiler/src/openxla/compiler/nvgpu/Dialect/TritonFlow/Transforms/Passes.cpp, compiler/src/openxla/compiler/nvgpu/Dialect/TritonFlow/Transforms/Passes.h, compiler/src/openxla/compiler/nvgpu/Dialect/TritonFlow/Transforms/Passes.td, compiler/src/openxla/compiler/nvgpu/Dialect/TritonFlow/Transforms/test/BUILD.bazel, compiler/src/openxla/compiler/nvgpu/Dialect/TritonFlow/Transforms/test/CMakeLists.txt, compiler/src/openxla/compiler/nvgpu/Dialect/TritonFlow/Transforms/test/outline_triton_calls.mlir
Diff: https://github.com/ezhulenev/openxla-nvgpu/compare/triton-2...ezhulenev:openxla-nvgpu:triton-3
=> [Triton] Add a pass to outline triton functions into executables

compiler/src/openxla/compiler/nvgpu/Dialect/TritonFlow/Conversion/ConvertHloToTriton.cpp, compiler/src/openxla/compiler/nvgpu/Dialect/TritonFlow/Transforms/test/hlo_to_triton.mlir, runtime/src/openxla/runtime/nvgpu/triton/test/CMakeLists.txt, runtime/src/openxla/runtime/nvgpu/triton/test/triton_add_inplace.mlir, runtime/src/openxla/runtime/nvgpu/triton/test/triton_add_inplace_bytecode.mlir, runtime/src/openxla/runtime/nvgpu/triton/test/triton_custom_call_add_inplace.mlir
Convert mhlo custom call operand aliases to Triton tied operands
=> [Triton] Add support for custom call operand aliases

compiler/src/openxla/compiler/nvgpu/Dialect/CUDNN/Conversion/ConvertCUDNNToRuntime.cpp, compiler/src/openxla/compiler/nvgpu/Dialect/CUDNN/Transforms/ConvertCUDNNToRuntime.cpp, compiler/src/openxla/compiler/nvgpu/Dialect/TritonFlow/Conversion/BUILD.bazel, compiler/src/openxla/compiler/nvgpu/Dialect/TritonFlow/Conversion/CMakeLists.txt, compiler/src/openxla/compiler/nvgpu/Dialect/TritonFlow/Conversion/ConvertHloToTriton.cpp, compiler/src/openxla/compiler/nvgpu/Dialect/TritonFlow/Transforms/ConvertHloToTriton.cpp, compiler/src/openxla/compiler/nvgpu/Dialect/TritonFlow/Transforms/PassDetail.h, compiler/src/openxla/compiler/nvgpu/Dialect/TritonFlow/Transforms/Passes.td, runtime/src/openxla/runtime/nvgpu/cudnn/CMakeLists.txt, sync_deps.py
This only fixes build errors. Multiple test errors remain.
=> Update to latest IREE version

compiler/src/openxla/compiler/nvgpu/Dialect/CUDNN/Conversion/ConvertCUDNNToRuntime.cpp, compiler/src/openxla/compiler/nvgpu/Dialect/CUDNN/Transforms/test/cudnn_to_runtime.mlir, runtime/src/openxla/runtime/nvgpu/cudnn/cudnn_module.cpp
This patch will add support for ReLU lowering in
compiler plugin and runtime.
Fixes issue https://github.com/openxla/openxla-nvgpu/issues/123
=> Added lowering from cudnn.relu and relu custom call

build_tools/third_party/triton/CMakeLists.txt
Update CMake build after updating Triton, all triton tests pass now: `ctest --test-dir build -R triton`
=> [Triton] Fix Triton build after sync to latest version
